const seg=(exerciseId,minutes=5)=>({exerciseId,minutes});
const program=(id,title,level,focus,ids)=>({id,title,trainingType:'reformer',level,focus,duration:50,segments:ids.map(x=>seg(x,5))});
export const reformerProgramCategories=['Full Body','Lower Body','Upper Body','Core','Glutes & Legs','Back & Posture','Strength','Mobility','Stretching'];
export const reformerPrograms=[
program('rf-b-full','Beginner Full Body 50','Beginner','Full Body',['reformer:footwork_parallel','reformer:footwork_toes','reformer:running','reformer:rowing_back','reformer:chest_expansion','reformer:hug_tree','reformer:hundred_straps','reformer:knee_stretches_round','reformer:mermaid','reformer:hamstring_stretch']),
program('rf-a-full','Advanced Full Body 50','Advanced','Full Body',['reformer:single_leg_press','reformer:scooter','reformer:side_split','reformer:pulling_straps','reformer:t_pull','reformer:kneeling_chest_press','reformer:plank_pike','reformer:coordination','reformer:down_stretch','reformer:semi_circle']),
program('rf-b-lower','Beginner Lower Body 50','Beginner','Lower Body',['reformer:footwork_parallel','reformer:footwork_toes','reformer:footwork_v','reformer:running','reformer:heel_lower_lift','reformer:footwork_parallel','reformer:running','reformer:heel_lower_lift','reformer:hip_flexor_stretch','reformer:hamstring_stretch']),
program('rf-a-legs','Advanced Glutes & Legs 50','Advanced','Glutes & Legs',['reformer:single_leg_press','reformer:scooter','reformer:front_split','reformer:side_split','reformer:single_leg_press','reformer:scooter','reformer:front_split','reformer:side_split','reformer:down_stretch','reformer:semi_circle']),
program('rf-b-upper','Beginner Upper Body 50','Beginner','Upper Body',['reformer:rowing_back','reformer:chest_expansion','reformer:hug_tree','reformer:biceps_curl','reformer:triceps_press','reformer:salute','reformer:arm_circles','reformer:rowing_back','reformer:mermaid','reformer:hamstring_stretch']),
program('rf-a-upper','Advanced Upper Body Strength 50','Advanced','Strength',['reformer:pulling_straps','reformer:t_pull','reformer:backstroke','reformer:kneeling_chest_press','reformer:long_stretch','reformer:kneeling_arm_press','reformer:long_box_triceps','reformer:coordination','reformer:down_stretch','reformer:semi_circle']),
program('rf-b-core','Beginner Core 50','Beginner','Core',['reformer:hundred_straps','reformer:knee_stretches_round','reformer:knee_stretches_flat','reformer:footwork_parallel','reformer:rowing_back','reformer:hundred_straps','reformer:knee_stretches_round','reformer:knee_stretches_flat','reformer:mermaid','reformer:hamstring_stretch']),
program('rf-a-core','Advanced Core 50','Advanced','Core',['reformer:plank_pike','reformer:long_back_stretch','reformer:coordination','reformer:long_stretch','reformer:kneeling_arm_press','reformer:plank_pike','reformer:coordination','reformer:long_back_stretch','reformer:down_stretch','reformer:semi_circle']),
program('rf-b-posture','Beginner Back & Posture 50','Beginner','Back & Posture',['reformer:elephant','reformer:rowing_back','reformer:chest_expansion','reformer:arm_circles','reformer:salute','reformer:elephant','reformer:rowing_back','reformer:hug_tree','reformer:mermaid','reformer:hamstring_stretch']),
program('rf-b-mobility','Beginner Mobility & Stretching 50','Beginner','Mobility',['reformer:mermaid','reformer:hip_flexor_stretch','reformer:hamstring_stretch','reformer:calf_stretch','reformer:elephant','reformer:mermaid','reformer:hip_flexor_stretch','reformer:hamstring_stretch','reformer:calf_stretch','reformer:running']),
program('rf-a-mobility','Advanced Mobility & Stretching 50','Advanced','Stretching',['reformer:front_split','reformer:side_split','reformer:down_stretch','reformer:semi_circle','reformer:plank_pike','reformer:front_split','reformer:side_split','reformer:down_stretch','reformer:semi_circle','reformer:coordination'])
];
