export const REFORMER_CATEGORIES=['Πόδια','Πλάτη','Στήθος','Κοιλιακοί / Κορμός','Χέρια / Βραχίονες','Stretching'];
export const REFORMER_LEVELS=['Beginner','Advanced'];
const visuals=()=>({start:null,execution:null,return:null,gif:null,video:null,model3d:null});
const ex=(id,name,gr,category,level,spring,footbar,straps,reps,tags=[])=>({
 id:`reformer:${id}`,name,gr,trainingType:'reformer',group:category,bodyArea:category,equipment:'Pilates Reformer',level,
 primaryMuscles:[category],secondaryMuscles:[],goal:category==='Stretching'?'Mobility':'Control',
 description:`${gr} στο Pilates Reformer με έμφαση στον έλεγχο, την αναπνοή και την ακρίβεια.`,
 startPosition:'Τοποθετήσου στο Reformer με ουδέτερη σπονδυλική θέση και σταθερή λεκάνη.',
 instructions:'Κίνησε το carriage ελεγχόμενα, χωρίς απότομα τελειώματα, διατηρώντας σωστή ευθυγράμμιση.',
 returnDescription:'Επέστρεψε αργά στην αρχική θέση χωρίς να χάνεις τον έλεγχο της αντίστασης.',
 breathing:'Εισπνοή στην προετοιμασία, εκπνοή στο κύριο μέρος της προσπάθειας.',
 reps,cues:['Σταθερή λεκάνη','Μακρύς αυχένας','Έλεγχος του carriage'],
 mistakes:['Απότομη επιστροφή carriage','Υπερέκταση μέσης','Απώλεια ευθυγράμμισης'],
 regression:'Μείωσε εύρος ή αντίσταση και επίλεξε πιο σταθερή θέση.',
 progression:'Αύξησε αντίσταση, εύρος ή μονομερή απαίτηση μόνο με πλήρη έλεγχο.',
 springSetting:spring,footbarPosition:footbar,straps,safety:'Ρύθμισε springs και stop position πριν την έναρξη. Διακοπή αν υπάρχει πόνος.',tags,visuals:visuals()
});
export const reformerExercises=[
ex('footwork_parallel','Footwork Parallel Heels','Footwork παράλληλα στις φτέρνες','Πόδια','Beginner','Medium-Heavy','Up','No','10–15',['footwork']),
ex('footwork_toes','Footwork Parallel Toes','Footwork παράλληλα στα δάχτυλα','Πόδια','Beginner','Medium-Heavy','Up','No','10–15',['footwork']),
ex('footwork_v','Pilates V Footwork','Footwork Pilates V','Πόδια','Beginner','Medium-Heavy','Up','No','10–15',['footwork']),
ex('single_leg_press','Single-Leg Footwork','Μονόποδο footwork','Πόδια','Advanced','Medium','Up','No','8–12 / πόδι',['single-leg']),
ex('running','Running on Reformer','Running στο Reformer','Πόδια','Beginner','Medium','Up','No','20–30 εναλλαγές',['calves']),
ex('heel_lower_lift','Heel Lower & Lift','Κάθοδος και άνοδος φτέρνας','Πόδια','Beginner','Medium','Up','No','10–15',['calves']),
ex('side_split','Standing Side Split','Όρθιο side split','Πόδια','Advanced','Light-Medium','Down','No','6–10',['adductors','abductors']),
ex('front_split','Front Split','Front split στο Reformer','Πόδια','Advanced','Light','Down','No','6–8',['lunge']),
ex('scooter','Scooter','Scooter','Πόδια','Advanced','Light-Medium','Down','No','8–12 / πόδι',['glutes']),
ex('elephant','Elephant','Elephant','Πλάτη','Beginner','Medium','Down','No','8–12',['posterior-chain']),
ex('rowing_back','Rowing Back','Rowing πλάτης','Πλάτη','Beginner','Light-Medium','Down','Hands','8–12',['rowing']),
ex('pulling_straps','Pulling Straps','Pulling straps','Πλάτη','Advanced','Light','Down','Hands','8–12',['long-box']),
ex('t_pull','T Pull','T pull στο long box','Πλάτη','Advanced','Light','Down','Hands','8–12',['long-box']),
ex('backstroke','Backstroke','Backstroke','Πλάτη','Advanced','Light','Down','Hands','6–10',['long-box']),
ex('chest_expansion','Chest Expansion','Chest expansion','Στήθος','Beginner','Light-Medium','Down','Hands','8–12',['arms']),
ex('hug_tree','Hug a Tree','Hug a tree','Στήθος','Beginner','Light','Down','Hands','8–12',['chest']),
ex('kneeling_chest_press','Kneeling Chest Press','Γονατιστές πιέσεις στήθους','Στήθος','Advanced','Light-Medium','Down','Hands','8–12',['kneeling']),
ex('long_stretch','Long Stretch','Long stretch','Στήθος','Advanced','Medium','Up','No','6–10',['plank']),
ex('hundred_straps','Hundred with Straps','Hundred με straps','Κοιλιακοί / Κορμός','Beginner','Light','Down','Hands','60–100 παλμοί',['core']),
ex('knee_stretches_round','Knee Stretches Round','Knee stretch με στρογγυλή πλάτη','Κοιλιακοί / Κορμός','Beginner','Medium','Down','No','8–12',['core']),
ex('knee_stretches_flat','Knee Stretches Flat','Knee stretch με επίπεδη πλάτη','Κοιλιακοί / Κορμός','Beginner','Medium','Down','No','8–12',['core']),
ex('plank_pike','Plank to Pike','Plank σε pike','Κοιλιακοί / Κορμός','Advanced','Light-Medium','Down','No','6–10',['core','plank']),
ex('long_back_stretch','Long Back Stretch','Long back stretch','Κοιλιακοί / Κορμός','Advanced','Medium','Up','No','6–8',['core']),
ex('coordination','Coordination','Coordination','Κοιλιακοί / Κορμός','Advanced','Light','Down','Hands','6–10',['coordination']),
ex('biceps_curl','Seated Biceps Curl','Καθιστές κάμψεις δικεφάλων','Χέρια / Βραχίονες','Beginner','Light','Down','Hands','8–12',['arms']),
ex('triceps_press','Kneeling Triceps Press','Γονατιστές εκτάσεις τρικεφάλων','Χέρια / Βραχίονες','Beginner','Light','Down','Hands','8–12',['arms']),
ex('salute','Salute','Salute','Χέρια / Βραχίονες','Beginner','Light','Down','Hands','8–12',['arms']),
ex('arm_circles','Arm Circles','Κύκλοι χεριών','Χέρια / Βραχίονες','Beginner','Light','Down','Hands','8–12',['arms']),
ex('kneeling_arm_press','Kneeling Arm Press','Γονατιστές πιέσεις χεριών','Χέρια / Βραχίονες','Advanced','Light-Medium','Down','Hands','8–12',['arms','stability']),
ex('long_box_triceps','Long Box Triceps Press','Τρικέφαλοι σε long box','Χέρια / Βραχίονες','Advanced','Light','Down','Hands','8–12',['long-box']),
ex('mermaid','Mermaid','Mermaid διάταση','Stretching','Beginner','Light','Up','No','4–6 / πλευρά',['lateral-flexion']),
ex('hip_flexor_stretch','Hip Flexor Stretch','Διάταση καμπτήρων ισχίου','Stretching','Beginner','Light','Down','No','30–45s / πλευρά',['hips']),
ex('hamstring_stretch','Hamstring Stretch','Διάταση οπίσθιων μηριαίων','Stretching','Beginner','Light','Down','Feet','30–45s',['hamstrings']),
ex('calf_stretch','Calf Stretch','Διάταση γάμπας','Stretching','Beginner','Medium','Up','No','30–45s / πλευρά',['calves']),
ex('down_stretch','Down Stretch','Down stretch','Stretching','Advanced','Medium','Down','No','6–8',['front-body']),
ex('semi_circle','Semi-Circle','Semi-circle','Stretching','Advanced','Medium','Up','No','6–8',['spine','hips'])
];
