// Verified curated Functional media aliases.
// Only exact, reviewed source exercise names are allowed here.
// A mapping is used only when the source record exists at runtime; otherwise the UI falls back safely.
export const CURATED_GIF_NAME_MAP={
  'local:push_up':'push-up',
  'local:squat':'squat',
  'local:reverse_lunge':'reverse lunge',
  'local:lunge':'forward lunge',
  'local:plank':'plank',
  'local:burpee':'burpee',
  'local:mountain_climber':'mountain climber',
  'local:side_plank':'side plank',
  'local:split_squat':'split squat',
  'local:lateral_lunge':'lateral lunge',
  'local:dead_bug':'dead bug',
  'local:back_squat':'barbell back squat',
  'local:front_squat':'barbell front squat',
  'local:deadlift':'barbell deadlift',
  'local:romanian_deadlift':'romanian deadlift',
  'local:bent_over_row':'barbell bent over row',
  'local:overhead_press':'barbell overhead press',
  'local:push_press':'barbell push press',
  'local:thruster':'barbell thruster',
  'local:dumbbell_goblet_squat':'dumbbell goblet squat',
  'local:dumbbell_reverse_lunge':'dumbbell reverse lunge',
  'local:dumbbell_split_squat':'dumbbell split squat',
  'local:dumbbell_romanian_deadlift':'dumbbell romanian deadlift',
  'local:dumbbell_row':'one arm dumbbell row',
  'local:dumbbell_floor_press':'dumbbell floor press',
  'local:dumbbell_shoulder_press':'dumbbell shoulder press',
  'local:dumbbell_thruster':'dumbbell thruster',
  'local:renegade_row':'renegade row',
  'local:dumbbell_snatch':'dumbbell snatch',
  'local:farmer_carry':'farmer carry',
  'local:kettlebell_swing':'kettlebell swing',
  'local:kettlebell_goblet_squat':'kettlebell goblet squat',
  'local:kettlebell_clean':'kettlebell clean',
  'local:kettlebell_snatch':'kettlebell snatch',
  'local:turkish_get_up':'turkish get up',
  'local:wall_sit':'wall sit',
  'local:jump_squat':'jump squat',
  'local:cossack_squat':'cossack squat',
  'local:walking_lunge':'walking lunge',
  'local:step_up':'step up',
  'local:bulgarian_split_squat':'bulgarian split squat',
  'local:single_leg_rdl':'single leg romanian deadlift',
  'local:glute_bridge':'glute bridge',
  'local:hip_thrust':'hip thrust',
  'local:standing_calf_raise':'standing calf raise',
  'local:incline_push_up':'incline push-up',
  'local:decline_push_up':'decline push-up',
  'local:close_grip_push_up':'close-grip push-up',
  'local:wide_push_up':'wide push-up',
  'local:pike_push_up':'pike push-up',
  'local:dumbbell_bench_press':'dumbbell bench press',
  'local:arnold_press':'arnold press',
  'local:dumbbell_lateral_raise':'dumbbell lateral raise',
  'local:dumbbell_front_raise':'dumbbell front raise',
  'local:dumbbell_biceps_curl':'dumbbell biceps curl',
  'local:hammer_curl':'hammer curl',
  'local:overhead_triceps_extension':'dumbbell overhead triceps extension',
  'local:crunch':'crunch',
  'local:bicycle_crunch':'bicycle crunch',
  'local:reverse_crunch':'reverse crunch',
  'local:lying_leg_raise':'lying leg raise',
  'local:russian_twist':'russian twist',
  'local:plank_jack':'plank jack',
  'local:cross_body_mountain_climber':'cross body mountain climber',
  'local:kettlebell_deadlift':'kettlebell deadlift',
  'local:kettlebell_rdl':'kettlebell romanian deadlift',
  'local:kettlebell_sumo_deadlift':'kettlebell sumo deadlift',
  'local:kettlebell_press':'kettlebell press',
  'local:kettlebell_high_pull':'kettlebell high pull',
  'local:kettlebell_halo':'kettlebell halo',
  'local:kettlebell_windmill':'kettlebell windmill',
  'local:dumbbell_step_up':'dumbbell step up',
  'local:dumbbell_lateral_lunge':'dumbbell lateral lunge',
  'local:dumbbell_bulgarian_split_squat':'dumbbell bulgarian split squat',
  'local:dumbbell_single_leg_rdl':'dumbbell single leg romanian deadlift',
  'local:dumbbell_hip_thrust':'dumbbell hip thrust',
  'local:dumbbell_calf_raise':'dumbbell standing calf raise',
  'local:box_squat':'box squat',
  'local:bench_dip':'bench dip',
  'local:hip_flexor_stretch':'hip flexor stretch',
  'local:cat_cow':'cat cow',
  'local:childs_pose':'child pose'
};

export const resolveCuratedGif=(exercise,byName)=>{
  const exact=byName.get(exercise.name);
  if(exact) return exact;
  const alias=CURATED_GIF_NAME_MAP[exercise.id];
  return alias?byName.get(alias)||null:null;
};
