// Canonical Functional catalogue. Difficulty belongs to programs, never individual exercises.
// No guessed GLB URLs: verified 3D media is merged at runtime from the remote manifest.
const rows=[
['push_up','Push-Up','Κάμψεις','Στήθος','Bodyweight','Push','Strength'],['squat','Squat','Καθίσματα','Πόδια','Bodyweight','Squat','Strength'],['reverse_lunge','Reverse Lunge','Προβολές πίσω','Πόδια','Bodyweight','Lunge','Stability'],['lunge','Forward Lunge','Προβολές μπροστά','Πόδια','Bodyweight','Lunge','Strength'],['plank','Plank','Σανίδα','Κορμός','Bodyweight','Anti-extension','Core'],['burpee','Burpee','Burpee','Full Body','Bodyweight','Full Body','Conditioning'],['mountain_climber','Mountain Climber','Ορειβάτης','Κορμός','Bodyweight','Locomotion','Conditioning'],['bear_crawl','Bear Crawl','Bear Crawl','Full Body','Bodyweight','Locomotion','Conditioning'],['side_plank','Side Plank','Πλάγια σανίδα','Κορμός','Bodyweight','Anti-lateral flexion','Core'],['plank_shoulder_tap','Plank Shoulder Tap','Σανίδα με άγγιγμα ώμων','Κορμός','Bodyweight','Anti-rotation','Stability'],['split_squat','Split Squat','Split Squat','Πόδια','Bodyweight','Lunge','Strength'],['lateral_lunge','Lateral Lunge','Πλάγια προβολή','Πόδια','Bodyweight','Lateral','Mobility'],['single_leg_glute_bridge','Single-Leg Glute Bridge','Μονόποδη γέφυρα γλουτών','Γλουτοί','Bodyweight','Hinge','Stability'],['inchworm','Inchworm','Inchworm','Full Body','Bodyweight','Locomotion','Mobility'],['dead_bug','Dead Bug','Dead Bug','Κορμός','Bodyweight','Anti-extension','Core'],
['back_squat','Barbell Back Squat','Back Squat με μπάρα','Πόδια','Barbell','Squat','Strength'],['front_squat','Barbell Front Squat','Front Squat με μπάρα','Πόδια','Barbell','Squat','Strength'],['deadlift','Barbell Deadlift','Deadlift με μπάρα','Full Body','Barbell','Hinge','Strength'],['romanian_deadlift','Romanian Deadlift','Romanian Deadlift','Πόδια','Barbell','Hinge','Strength'],['bent_over_row','Bent-Over Row','Κωπηλατική σκυφτός με μπάρα','Πλάτη','Barbell','Pull','Strength'],['overhead_press','Overhead Press','Πιέσεις πάνω από το κεφάλι','Ώμοι','Barbell','Push','Strength'],['push_press','Push Press','Push Press','Full Body','Barbell','Push','Power'],['thruster','Barbell Thruster','Thruster με μπάρα','Full Body','Barbell','Squat + Push','Conditioning'],['hang_power_clean','Hang Power Clean','Hang Power Clean','Full Body','Barbell','Olympic / Hinge','Power'],['clean_and_press','Clean & Press','Clean & Press','Full Body','Barbell','Olympic + Push','Power'],['clean_and_jerk','Clean & Jerk','Clean & Jerk','Full Body','Barbell','Olympic','Power'],['snatch','Power Snatch','Power Snatch','Full Body','Barbell','Olympic','Power'],['sumo_high_pull','Sumo Deadlift High Pull','Sumo Deadlift High Pull','Full Body','Barbell','Hinge + Pull','Conditioning'],['overhead_squat','Overhead Squat','Overhead Squat','Full Body','Barbell','Squat + Stability','Mobility'],
['dumbbell_goblet_squat','Dumbbell Goblet Squat','Goblet Squat με αλτήρα','Πόδια','Dumbbells','Squat','Strength'],['dumbbell_reverse_lunge','Dumbbell Reverse Lunge','Προβολές πίσω με αλτήρες','Πόδια','Dumbbells','Lunge','Strength'],['dumbbell_split_squat','Dumbbell Split Squat','Split Squat με αλτήρες','Πόδια','Dumbbells','Lunge','Strength'],['dumbbell_romanian_deadlift','Dumbbell Romanian Deadlift','Romanian Deadlift με αλτήρες','Πόδια','Dumbbells','Hinge','Strength'],['dumbbell_row','One-Arm Dumbbell Row','Μονόχειρη κωπηλατική με αλτήρα','Πλάτη','Dumbbells','Pull','Strength'],['dumbbell_floor_press','Dumbbell Floor Press','Πιέσεις αλτήρων στο έδαφος','Στήθος','Dumbbells','Push','Strength'],['dumbbell_shoulder_press','Dumbbell Shoulder Press','Πιέσεις ώμων με αλτήρες','Ώμοι','Dumbbells','Push','Strength'],['dumbbell_thruster','Dumbbell Thruster','Thruster με αλτήρες','Full Body','Dumbbells','Squat + Push','Conditioning'],['renegade_row','Renegade Row','Renegade Row','Full Body','Dumbbells','Pull + Anti-rotation','Strength'],['dumbbell_clean_press','Dumbbell Clean & Press','Clean & Press με αλτήρες','Full Body','Dumbbells','Hinge + Push','Power'],['dumbbell_snatch','Dumbbell Snatch','Snatch με αλτήρα','Full Body','Dumbbells','Hinge + Pull','Power'],['farmer_carry','Farmer Carry','Μεταφορά Farmer','Full Body','Dumbbells','Carry','Strength'],['suitcase_carry','Suitcase Carry','Μονόπλευρη μεταφορά Suitcase','Κορμός','Dumbbells','Carry / Anti-lateral','Stability'],
['kettlebell_swing','Kettlebell Swing','Kettlebell Swing','Full Body','Kettlebell','Hinge','Conditioning'],['kettlebell_goblet_squat','Kettlebell Goblet Squat','Goblet Squat με kettlebell','Πόδια','Kettlebell','Squat','Strength'],['kettlebell_clean','Kettlebell Clean','Kettlebell Clean','Full Body','Kettlebell','Hinge + Pull','Power'],['kettlebell_clean_press','Kettlebell Clean & Press','Kettlebell Clean & Press','Full Body','Kettlebell','Hinge + Push','Power'],['kettlebell_snatch','Kettlebell Snatch','Kettlebell Snatch','Full Body','Kettlebell','Hinge + Pull','Power'],['turkish_get_up','Turkish Get-Up','Turkish Get-Up','Full Body','Kettlebell','Ground to Stand','Stability'],
['trx_row','TRX Row','Κωπηλατική TRX','Πλάτη','TRX','Pull','Strength'],['trx_squat','TRX Squat','Καθίσματα TRX','Πόδια','TRX','Squat','Strength'],['trx_reverse_lunge','TRX Reverse Lunge','Προβολές πίσω TRX','Πόδια','TRX','Lunge','Stability'],['trx_chest_press','TRX Chest Press','Πιέσεις στήθους TRX','Στήθος','TRX','Push','Strength'],['band_row','Resistance Band Row','Κωπηλατική με λάστιχο','Πλάτη','Resistance Bands','Pull','Strength'],['band_pallof_press','Pallof Press','Pallof Press με λάστιχο','Κορμός','Resistance Bands','Anti-rotation','Core'],['band_squat_press','Band Squat to Press','Squat to Press με λάστιχο','Full Body','Resistance Bands','Squat + Push','Conditioning'],['cable_row','Cable Row','Κωπηλατική τροχαλίας','Πλάτη','Cables','Pull','Strength'],['cable_woodchop','Cable Woodchop','Διαγώνια στροφή τροχαλίας','Κορμός','Cables','Rotation','Core'],['battle_rope_waves','Battle Rope Waves','Κύματα με battle ropes','Full Body','Battle Ropes','Conditioning','Conditioning'],['battle_rope_slam','Battle Rope Slam','Slams με battle ropes','Full Body','Battle Ropes','Full Body','Conditioning'],['bosu_squat','BOSU Squat','Καθίσματα σε BOSU','Πόδια','BOSU','Squat + Balance','Stability'],['bosu_push_up','BOSU Push-Up','Κάμψεις σε BOSU','Στήθος','BOSU','Push + Stability','Strength']];
// Curated Functional expansion. These entries intentionally use only the existing schema.
// When no verified GIF/GLB match exists, ExerciseAnimation safely falls back to MotionPreview.
const extraRows=[
['wall_sit','Wall Sit','Κάθισμα στον τοίχο','Πόδια','Bodyweight','Isometric Squat','Strength'],
['jump_squat','Jump Squat','Καθίσματα με άλμα','Πόδια','Bodyweight','Squat + Jump','Power'],
['pulse_squat','Pulse Squat','Καθίσματα με παλμούς','Πόδια','Bodyweight','Squat','Strength'],
['cossack_squat','Cossack Squat','Κοζάκικα καθίσματα','Πόδια','Bodyweight','Lateral Squat','Mobility'],
['curtsy_lunge','Curtsy Lunge','Διαγώνια προβολή πίσω','Πόδια','Bodyweight','Lunge','Strength'],
['walking_lunge','Walking Lunge','Περπατητές προβολές','Πόδια','Bodyweight','Lunge','Strength'],
['lunge_to_knee_drive','Lunge to Knee Drive','Προβολή με ανέβασμα γονάτου','Πόδια','Bodyweight','Lunge + Balance','Stability'],
['lateral_step_up','Lateral Step-Up','Πλάγιο ανέβασμα σε step','Πόδια','Bench/Step','Step-Up','Strength'],
['step_up','Step-Up','Ανέβασμα σε step','Πόδια','Bench/Step','Step-Up','Strength'],
['step_up_knee_drive','Step-Up to Knee Drive','Ανέβασμα σε step με γόνατο','Πόδια','Bench/Step','Step-Up + Balance','Stability'],
['bulgarian_split_squat','Bulgarian Split Squat','Βουλγάρικο split squat','Πόδια','Bench/Step','Split Squat','Strength'],
['single_leg_rdl','Single-Leg Romanian Deadlift','Μονόποδο Romanian Deadlift','Πόδια','Bodyweight','Single-Leg Hinge','Stability'],
['glute_bridge','Glute Bridge','Γέφυρα γλουτών','Γλουτοί','Bodyweight','Hinge','Strength'],
['hip_thrust','Hip Thrust','Hip Thrust','Γλουτοί','Bench/Step','Hinge','Strength'],
['single_leg_hip_thrust','Single-Leg Hip Thrust','Μονόποδο hip thrust','Γλουτοί','Bench/Step','Single-Leg Hinge','Strength'],
['standing_calf_raise','Standing Calf Raise','Άρσεις γάμπας όρθιος','Πόδια','Bodyweight','Calf Raise','Strength'],
['single_leg_calf_raise','Single-Leg Calf Raise','Μονόποδες άρσεις γάμπας','Πόδια','Bodyweight','Calf Raise','Stability'],
['lateral_shuffle','Lateral Shuffle','Πλάγια βήματα','Πόδια','Bodyweight','Lateral Locomotion','Conditioning'],
['skater_step','Skater Step','Πλάγιο βήμα skater','Πόδια','Bodyweight','Lateral','Stability'],
['skater_jump','Skater Jump','Πλάγιο άλμα skater','Πόδια','Bodyweight','Lateral Jump','Power'],
['incline_push_up','Incline Push-Up','Κάμψεις με τα χέρια ψηλά','Στήθος','Bench/Step','Push','Strength'],
['decline_push_up','Decline Push-Up','Κάμψεις με τα πόδια ψηλά','Στήθος','Bench/Step','Push','Strength'],
['close_grip_push_up','Close-Grip Push-Up','Κλειστές κάμψεις','Τρικέφαλοι','Bodyweight','Push','Strength'],
['wide_push_up','Wide Push-Up','Ανοιχτές κάμψεις','Στήθος','Bodyweight','Push','Strength'],
['pike_push_up','Pike Push-Up','Κάμψεις ώμων pike','Ώμοι','Bodyweight','Vertical Push','Strength'],
['dumbbell_bench_press','Dumbbell Bench Press','Πιέσεις στήθους με αλτήρες σε πάγκο','Στήθος','Dumbbells','Push','Strength'],
['alternating_dumbbell_press','Alternating Dumbbell Press','Εναλλάξ πιέσεις αλτήρων','Στήθος','Dumbbells','Push','Strength'],
['arnold_press','Arnold Press','Πιέσεις Arnold','Ώμοι','Dumbbells','Vertical Push','Strength'],
['single_arm_dumbbell_press','Single-Arm Dumbbell Shoulder Press','Μονόχειρες πιέσεις ώμων','Ώμοι','Dumbbells','Vertical Push','Strength'],
['dumbbell_lateral_raise','Dumbbell Lateral Raise','Πλάγιες άρσεις αλτήρων','Ώμοι','Dumbbells','Raise','Strength'],
['dumbbell_front_raise','Dumbbell Front Raise','Μπροστινές άρσεις αλτήρων','Ώμοι','Dumbbells','Raise','Strength'],
['rear_delt_fly','Dumbbell Rear Delt Fly','Ανοίγματα οπίσθιων ώμων','Ώμοι','Dumbbells','Horizontal Abduction','Strength'],
['chest_supported_row','Chest-Supported Dumbbell Row','Κωπηλατική με στήριξη στήθους','Πλάτη','Dumbbells','Pull','Strength'],
['dumbbell_pullover','Dumbbell Pullover','Pullover με αλτήρα','Πλάτη','Dumbbells','Pullover','Strength'],
['dumbbell_biceps_curl','Dumbbell Biceps Curl','Κάμψεις δικεφάλων με αλτήρες','Δικέφαλοι','Dumbbells','Elbow Flexion','Strength'],
['hammer_curl','Hammer Curl','Σφυροειδείς κάμψεις','Δικέφαλοι','Dumbbells','Elbow Flexion','Strength'],
['overhead_triceps_extension','Overhead Triceps Extension','Εκτάσεις τρικεφάλων πάνω από το κεφάλι','Τρικέφαλοι','Dumbbells','Elbow Extension','Strength'],
['dumbbell_triceps_kickback','Dumbbell Triceps Kickback','Εκτάσεις τρικεφάλων προς τα πίσω','Τρικέφαλοι','Dumbbells','Elbow Extension','Strength'],
['band_face_pull','Resistance Band Face Pull','Face pull με λάστιχο','Πλάτη','Resistance Bands','Pull','Strength'],
['band_pull_apart','Band Pull-Apart','Ανοίγματα λάστιχου','Πλάτη','Resistance Bands','Horizontal Pull','Strength'],
['band_chest_press','Resistance Band Chest Press','Πιέσεις στήθους με λάστιχο','Στήθος','Resistance Bands','Push','Strength'],
['band_shoulder_press','Resistance Band Shoulder Press','Πιέσεις ώμων με λάστιχο','Ώμοι','Resistance Bands','Vertical Push','Strength'],
['band_biceps_curl','Resistance Band Biceps Curl','Κάμψεις δικεφάλων με λάστιχο','Δικέφαλοι','Resistance Bands','Elbow Flexion','Strength'],
['band_triceps_pressdown','Resistance Band Triceps Pressdown','Πιέσεις τρικεφάλων με λάστιχο','Τρικέφαλοι','Resistance Bands','Elbow Extension','Strength'],
['bird_dog','Bird Dog','Bird Dog','Κορμός','Bodyweight','Anti-rotation','Core'],
['bird_dog_row','Bird Dog Row','Bird Dog με κωπηλατική','Κορμός','Dumbbells','Anti-rotation + Pull','Stability'],
['hollow_hold','Hollow Hold','Κράτημα hollow','Κορμός','Bodyweight','Anti-extension','Core'],
['hollow_rock','Hollow Rock','Hollow rock','Κορμός','Bodyweight','Anti-extension','Core'],
['crunch','Crunch','Ροκανίσματα','Κορμός','Bodyweight','Spinal Flexion','Core'],
['bicycle_crunch','Bicycle Crunch','Ποδήλατο κοιλιακών','Κορμός','Bodyweight','Rotation','Core'],
['reverse_crunch','Reverse Crunch','Ανάστροφα ροκανίσματα','Κορμός','Bodyweight','Spinal Flexion','Core'],
['lying_leg_raise','Lying Leg Raise','Άρσεις ποδιών ξαπλωτά','Κορμός','Bodyweight','Hip Flexion','Core'],
['flutter_kicks','Flutter Kicks','Ψαλιδάκια','Κορμός','Bodyweight','Hip Flexion','Core'],
['heel_taps','Heel Taps','Αγγίγματα φτέρνας','Κορμός','Bodyweight','Lateral Flexion','Core'],
['russian_twist','Russian Twist','Ρωσικές στροφές','Κορμός','Bodyweight','Rotation','Core'],
['seated_knee_tuck','Seated Knee Tuck','Μάζεμα γονάτων καθιστός','Κορμός','Bodyweight','Flexion','Core'],
['plank_knee_to_elbow','Plank Knee to Elbow','Σανίδα με γόνατο στον αγκώνα','Κορμός','Bodyweight','Anti-extension','Core'],
['plank_jack','Plank Jack','Plank jack','Κορμός','Bodyweight','Anti-extension + Conditioning','Conditioning'],
['side_plank_reach_through','Side Plank Reach-Through','Πλάγια σανίδα με πέρασμα χεριού','Κορμός','Bodyweight','Rotation','Core'],
['side_plank_hip_dip','Side Plank Hip Dip','Πλάγια σανίδα με βύθιση λεκάνης','Κορμός','Bodyweight','Anti-lateral flexion','Core'],
['high_plank_to_forearm','High Plank to Forearm Plank','Εναλλαγή ψηλής και χαμηλής σανίδας','Κορμός','Bodyweight','Anti-extension','Core'],
['cross_body_mountain_climber','Cross-Body Mountain Climber','Ορειβάτης χιαστί','Κορμός','Bodyweight','Rotation + Locomotion','Conditioning'],
['slow_mountain_climber','Slow Mountain Climber','Αργός ορειβάτης','Κορμός','Bodyweight','Anti-extension','Core'],
['bear_plank','Bear Plank','Σανίδα bear','Κορμός','Bodyweight','Anti-extension','Core'],
['dead_bug_band_pulldown','Dead Bug with Band Pulldown','Dead bug με έλξη λάστιχου','Κορμός','Resistance Bands','Anti-extension','Core'],
['half_kneeling_pallof_press','Half-Kneeling Pallof Press','Pallof press γονατιστός','Κορμός','Resistance Bands','Anti-rotation','Core'],
['standing_band_rotation','Standing Band Rotation','Όρθιες στροφές με λάστιχο','Κορμός','Resistance Bands','Rotation','Core'],
['dumbbell_russian_twist','Dumbbell Russian Twist','Ρωσικές στροφές με αλτήρα','Κορμός','Dumbbells','Rotation','Core'],
['thruster_single_dumbbell','Single-Dumbbell Thruster','Thruster με έναν αλτήρα','Full Body','Dumbbells','Squat + Push','Conditioning'],
['squat_to_press','Dumbbell Squat to Press','Squat to press με αλτήρες','Full Body','Dumbbells','Squat + Push','Conditioning'],
['devil_press','Devil Press','Devil press','Full Body','Dumbbells','Burpee + Hinge + Press','Power'],
['man_maker','Man Maker','Man maker','Full Body','Dumbbells','Complex','Power'],
['dumbbell_clean_squat_press','Dumbbell Clean Squat Press','Clean, squat και press με αλτήρες','Full Body','Dumbbells','Complex','Power'],
['dumbbell_deadlift_high_pull','Dumbbell Deadlift High Pull','Deadlift high pull με αλτήρες','Full Body','Dumbbells','Hinge + Pull','Conditioning'],
['burpee_to_box_step','Burpee to Step-Up','Burpee με ανέβασμα σε step','Full Body','Bench/Step','Burpee + Step-Up','Conditioning'],
['burpee_broad_jump','Burpee Broad Jump','Burpee με άλμα μπροστά','Full Body','Bodyweight','Burpee + Jump','Power'],
['squat_thrust','Squat Thrust','Squat thrust','Full Body','Bodyweight','Full Body','Conditioning'],
['walkout_push_up','Walkout to Push-Up','Walkout με κάμψη','Full Body','Bodyweight','Locomotion + Push','Conditioning'],
['bear_crawl_shoulder_tap','Bear Crawl Shoulder Tap','Bear crawl με άγγιγμα ώμων','Full Body','Bodyweight','Locomotion + Anti-rotation','Stability'],
['crab_walk','Crab Walk','Βάδισμα crab','Full Body','Bodyweight','Locomotion','Conditioning'],
['kettlebell_deadlift','Kettlebell Deadlift','Deadlift με kettlebell','Πόδια','Kettlebell','Hinge','Strength'],
['kettlebell_rdl','Kettlebell Romanian Deadlift','Romanian Deadlift με kettlebell','Πόδια','Kettlebell','Hinge','Strength'],
['kettlebell_sumo_deadlift','Kettlebell Sumo Deadlift','Sumo deadlift με kettlebell','Πόδια','Kettlebell','Hinge','Strength'],
['kettlebell_press','Kettlebell Strict Press','Πιέσεις kettlebell','Ώμοι','Kettlebell','Vertical Push','Strength'],
['single_arm_kb_press','Single-Arm Kettlebell Press','Μονόχειρες πιέσεις kettlebell','Ώμοι','Kettlebell','Vertical Push','Strength'],
['kettlebell_high_pull','Kettlebell High Pull','High pull με kettlebell','Full Body','Kettlebell','Hinge + Pull','Power'],
['kettlebell_halo','Kettlebell Halo','Halo με kettlebell','Ώμοι','Kettlebell','Shoulder Mobility','Mobility'],
['kettlebell_windmill','Kettlebell Windmill','Windmill με kettlebell','Full Body','Kettlebell','Hinge + Rotation','Stability'],
['kettlebell_rack_carry','Kettlebell Rack Carry','Μεταφορά kettlebell στη θέση rack','Full Body','Kettlebell','Carry','Strength'],
['kettlebell_overhead_carry','Kettlebell Overhead Carry','Μεταφορά kettlebell πάνω από το κεφάλι','Full Body','Kettlebell','Carry + Stability','Stability'],
['kettlebell_suitcase_carry','Kettlebell Suitcase Carry','Μονόπλευρη μεταφορά kettlebell','Κορμός','Kettlebell','Carry / Anti-lateral','Stability'],
['kettlebell_front_rack_squat','Kettlebell Front Rack Squat','Καθίσματα με kettlebell σε rack','Πόδια','Kettlebell','Squat','Strength'],
['kettlebell_reverse_lunge','Kettlebell Reverse Lunge','Προβολές πίσω με kettlebell','Πόδια','Kettlebell','Lunge','Strength'],
['kettlebell_clean_squat_press','Kettlebell Clean Squat Press','Clean, squat και press με kettlebell','Full Body','Kettlebell','Complex','Power'],
['dumbbell_step_up','Dumbbell Step-Up','Ανέβασμα σε step με αλτήρες','Πόδια','Dumbbells','Step-Up','Strength'],
['dumbbell_lateral_lunge','Dumbbell Lateral Lunge','Πλάγια προβολή με αλτήρες','Πόδια','Dumbbells','Lateral Lunge','Strength'],
['dumbbell_bulgarian_split_squat','Dumbbell Bulgarian Split Squat','Βουλγάρικο split squat με αλτήρες','Πόδια','Dumbbells','Split Squat','Strength'],
['dumbbell_single_leg_rdl','Dumbbell Single-Leg Romanian Deadlift','Μονόποδο Romanian Deadlift με αλτήρες','Πόδια','Dumbbells','Single-Leg Hinge','Stability'],
['dumbbell_hip_thrust','Dumbbell Hip Thrust','Hip thrust με αλτήρα','Γλουτοί','Dumbbells','Hinge','Strength'],
['dumbbell_calf_raise','Dumbbell Calf Raise','Άρσεις γάμπας με αλτήρες','Πόδια','Dumbbells','Calf Raise','Strength'],
['band_lateral_walk','Band Lateral Walk','Πλάγια βήματα με λάστιχο','Γλουτοί','Resistance Bands','Lateral','Activation'],
['band_monster_walk','Band Monster Walk','Monster walk με λάστιχο','Γλουτοί','Resistance Bands','Lateral','Activation'],
['band_glute_bridge','Band Glute Bridge','Γέφυρα γλουτών με λάστιχο','Γλουτοί','Resistance Bands','Hinge','Activation'],
['band_clamshell','Band Clamshell','Clamshell με λάστιχο','Γλουτοί','Resistance Bands','Hip Abduction','Activation'],
['band_deadlift','Resistance Band Deadlift','Deadlift με λάστιχο','Πόδια','Resistance Bands','Hinge','Strength'],
['band_good_morning','Resistance Band Good Morning','Good morning με λάστιχο','Πόδια','Resistance Bands','Hinge','Strength'],
['band_reverse_lunge','Resistance Band Reverse Lunge','Προβολές πίσω με λάστιχο','Πόδια','Resistance Bands','Lunge','Strength'],
['band_lateral_raise','Resistance Band Lateral Raise','Πλάγιες άρσεις με λάστιχο','Ώμοι','Resistance Bands','Raise','Strength'],
['band_external_rotation','Band External Rotation','Εξωτερικές στροφές ώμου με λάστιχο','Ώμοι','Resistance Bands','Shoulder Rotation','Activation'],
['trx_y_raise','TRX Y Raise','TRX Y raise','Ώμοι','TRX','Raise','Strength'],
['trx_face_pull','TRX Face Pull','TRX face pull','Πλάτη','TRX','Pull','Strength'],
['trx_hamstring_curl','TRX Hamstring Curl','Κάμψεις μηριαίων με TRX','Πόδια','TRX','Knee Flexion','Strength'],
['trx_glute_bridge','TRX Glute Bridge','Γέφυρα γλουτών με TRX','Γλουτοί','TRX','Hinge','Strength'],
['trx_plank','TRX Plank','Σανίδα TRX','Κορμός','TRX','Anti-extension','Core'],
['trx_knee_tuck','TRX Knee Tuck','Μάζεμα γονάτων TRX','Κορμός','TRX','Flexion','Core'],
['trx_pike','TRX Pike','TRX pike','Κορμός','TRX','Anti-extension + Pike','Core'],
['cable_pallof_press','Cable Pallof Press','Pallof press στην τροχαλία','Κορμός','Cables','Anti-rotation','Core'],
['cable_chest_press','Cable Chest Press','Πιέσεις στήθους στην τροχαλία','Στήθος','Cables','Push','Strength'],
['cable_face_pull','Cable Face Pull','Face pull στην τροχαλία','Πλάτη','Cables','Pull','Strength'],
['cable_rotation','Cable Rotation','Στροφές κορμού στην τροχαλία','Κορμός','Cables','Rotation','Core'],
['battle_rope_alternating_waves','Battle Rope Alternating Waves','Εναλλάξ κύματα με battle ropes','Full Body','Battle Ropes','Conditioning','Conditioning'],
['battle_rope_side_waves','Battle Rope Side-to-Side Waves','Πλάγια κύματα με battle ropes','Full Body','Battle Ropes','Conditioning','Conditioning'],
['battle_rope_power_slam','Battle Rope Power Slam','Δυνατά slams με battle ropes','Full Body','Battle Ropes','Full Body','Conditioning'],
['box_squat','Box Squat','Καθίσματα σε box','Πόδια','Bench/Step','Squat','Strength'],
['bench_dip','Bench Dip','Βυθίσεις τρικεφάλων σε πάγκο','Τρικέφαλοι','Bench/Step','Push','Strength'],
['bench_push_up','Bench Push-Up','Κάμψεις σε πάγκο','Στήθος','Bench/Step','Push','Strength'],
['hip_flexor_stretch','Hip Flexor Stretch','Διάταση καμπτήρων ισχίου','Πόδια','Bodyweight','Stretching','Mobility'],
['hamstring_sweep','Hamstring Sweep','Δυναμική διάταση οπίσθιων μηριαίων','Πόδια','Bodyweight','Dynamic Mobility','Mobility'],
['worlds_greatest_stretch','World’s Greatest Stretch','Δυναμική διάταση προβολής με στροφή','Full Body','Bodyweight','Dynamic Mobility','Mobility'],
['thoracic_rotation','Quadruped Thoracic Rotation','Θωρακική στροφή στα τέσσερα','Κορμός','Bodyweight','Mobility','Mobility'],
['cat_cow','Cat-Cow','Cat-cow','Κορμός','Bodyweight','Spinal Mobility','Mobility'],
['ankle_rocker','Ankle Rocker','Κινητοποίηση ποδοκνημικής','Πόδια','Bodyweight','Ankle Mobility','Mobility'],
['shoulder_circles','Shoulder Circles','Κύκλοι ώμων','Ώμοι','Bodyweight','Shoulder Mobility','Mobility'],
['arm_swings','Arm Swings','Αιωρήσεις χεριών','Ώμοι','Bodyweight','Dynamic Mobility','Mobility'],
['glute_activation_bridge','Glute Bridge Activation','Ενεργοποίηση γλουτών με γέφυρα','Γλουτοί','Bodyweight','Activation','Activation'],
['bodyweight_good_morning','Bodyweight Good Morning','Good morning χωρίς βάρος','Πόδια','Bodyweight','Hinge','Mobility'],
['deep_squat_pry','Deep Squat Pry','Βαθύ κάθισμα με κινητοποίηση','Πόδια','Bodyweight','Squat Mobility','Mobility'],
['calf_stretch','Standing Calf Stretch','Διάταση γάμπας όρθιος','Πόδια','Bodyweight','Stretching','Mobility'],
['childs_pose','Child’s Pose','Θέση παιδιού','Κορμός','Bodyweight','Stretching','Mobility'],
['kneeling_lat_stretch','Kneeling Lat Stretch','Διάταση πλάτης γονατιστός','Πλάτη','Bench/Step','Stretching','Mobility']
];
rows.push(...extraRows);
const defaultAliases={push_up:['καμψεις','push up'],squat:['καθισματα'],plank:['σανιδα'],burpee:['μπερπι'],mountain_climber:['ορειβατης'],romanian_deadlift:['rdl'],kettlebell_swing:['swing'],kettlebell_goblet_squat:['goblet squat'],turkish_get_up:['get up'],band_pallof_press:['pallof'],dumbbell_romanian_deadlift:['rdl με αλτηρες']};

const conditioning=new Set(['Conditioning','Power']);
export const exercises=rows.map(([id,name,gr,group,equipment,movement,goal])=>({id:`local:${id}`,openGymId:id,name,gr,aliases:defaultAliases[id]||[],group,equipment,primaryMuscles:[group],secondaryMuscles:group==='Κορμός'?['Γλουτοί','Σταθεροποιητές ώμων']:['Κορμός','Σταθεροποιητές'],movement,goal,instructions:`Εκτέλεσε ${gr} με ελεγχόμενο ρυθμό, ουδέτερη σπονδυλική στήλη και ασφαλές εύρος κίνησης.`,cues:['Σταθερός κορμός','Έλεγξε την τροχιά','Ποιότητα πριν από ταχύτητα'],mistakes:['Απώλεια ουδέτερης θέσης','Βιαστική εκτέλεση','Εύρος κίνησης χωρίς έλεγχο'],regression:'Μείωσε φορτίο, εύρος ή ταχύτητα και χρησιμοποίησε σταθερότερη παραλλαγή.',progression:'Αύξησε σταδιακά φορτίο, εύρος, πυκνότητα ή πολυπλοκότητα μόνο με άριστη τεχνική.',reps:conditioning.has(goal)?'30–45s':'8–12 επαναλήψεις',rest:conditioning.has(goal)?30:45,safety:'Σταμάτησε αν υπάρχει πόνος. Προσαρμόζεις φορτίο και εύρος στην τεχνική σου.'}));
