export const exercises=[
{id:1,name:'Push-up',gr:'Κάμψεις',group:'Στήθος',equipment:'Bodyweight',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Κράτησε το σώμα σε ευθεία γραμμή και κατέβασε ελεγχόμενα το στήθος.',cues:['Σταθερός κορμός','Ώμοι μακριά από τα αυτιά','Έλεγχος στην κάθοδο'],cue:'Σταθερός κορμός',mistakes:['Πτώση της λεκάνης'],regression:'Κάμψεις με γόνατα.',progression:'Πρόσθεσε παύση χαμηλά.',reps:'10–12 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-1',type:'placeholder',motion:'pushup'},media3d:{type:'glb',modelUrl:'https://assiamahs.github.io/opengym3d/assets/push_up.glb',animationName:'pushup',duration:5,loop:true,camera:{position:[2.8,1.7,4.2],target:[0,1,0]}}},
{id:2,name:'Bodyweight Squat',gr:'Καθίσματα',group:'Πόδια',equipment:'Bodyweight',level:'Beginner',goal:'Strength',secondary:[],instructions:'Κάθισε προς τα πίσω με τα γόνατα να ακολουθούν τη γραμμή των πελμάτων.',cues:['Στήθος ψηλά','Γόνατα στην ίδια κατεύθυνση με τα πέλματα','Πίεσε το έδαφος'],cue:'Στήθος ψηλά',mistakes:['Γόνατα προς τα μέσα'],regression:'Μικρότερο βάθος.',progression:'Goblet squat.',reps:'10–12 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-2',type:'placeholder',motion:'squat'}},
{id:3,name:'Reverse Lunge',gr:'Προβολές πίσω',group:'Πόδια',equipment:'Bodyweight',level:'Beginner',goal:'Strength',secondary:[],instructions:'Κάνε βήμα πίσω και χαμήλωσε ελεγχόμενα.',cues:['Κορμός όρθιος','Μπροστινό πέλμα σταθερό','Έλεγξε το γόνατο'],cue:'Κορμός όρθιος',mistakes:['Αστάθεια γονάτου'],regression:'Μικρότερο βήμα.',progression:'Πρόσθεσε αλτήρες.',reps:'10/πλευρά',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-3',type:'placeholder',motion:'lunge'}},
{id:4,name:'Plank',gr:'Σανίδα',group:'Κορμός',equipment:'Bodyweight',level:'Beginner',goal:'Endurance',secondary:[],instructions:'Κράτησε κεφάλι, ώμους, ισχία και φτέρνες σε ευθεία.',cues:['Σφίξε γλουτούς','Μάζεψε πλευρά','Ανάπνεε'],cue:'Σταθερός κορμός',mistakes:['Πτώση μέσης'],regression:'Στήριξη στα γόνατα.',progression:'Μετατόπιση βάρους.',reps:'30–45s',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-4',type:'placeholder',motion:'plank'}},
{id:5,name:'Mountain Climber',gr:'Mountain Climber',group:'Κορμός',equipment:'Bodyweight',level:'Intermediate',goal:'Conditioning',secondary:[],instructions:'Από σανίδα φέρε εναλλάξ τα γόνατα προς το στήθος.',cues:['Χέρια κάτω από ώμους','Λεκάνη σταθερή','Ρυθμική αναπνοή'],cue:'Λεκάνη σταθερή',mistakes:['Υπερβολική αναπήδηση'],regression:'Αργός ρυθμός.',progression:'Γρηγορότερος ρυθμός.',reps:'30–45s',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-5',type:'placeholder',motion:'plank'}},
{id:6,name:'Burpee',gr:'Burpee',group:'Full Body',equipment:'Bodyweight',level:'Advanced',goal:'Conditioning',secondary:[],instructions:'Κατέβασε τα χέρια, πήγαινε σε σανίδα και επέστρεψε σε όρθια θέση.',cues:['Έλεγξε την προσγείωση','Σταθερός κορμός','Ρυθμός χωρίς βιασύνη'],cue:'Έλεγξε την προσγείωση',mistakes:['Κακή προσγείωση'],regression:'Χωρίς άλμα.',progression:'Πρόσθεσε push-up.',reps:'8–10 επαναλήψεις',rest:40,safety:'Σταμάτησε αν υπάρχει πόνος ή ζάλη.',media:{id:'local-6',type:'placeholder',motion:'burpee'}},
{id:7,name:'Dumbbell Shoulder Press',gr:'Πιέσεις ώμων με αλτήρες',group:'Ώμοι',equipment:'Αλτήρες',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Πίεσε τους αλτήρες πάνω από το κεφάλι χωρίς υπερέκταση στη μέση.',cues:['Πλευρά μέσα','Καρποί ουδέτεροι','Έλεγξε την κάθοδο'],cue:'Πλευρά μέσα',mistakes:['Υπερέκταση μέσης'],regression:'Ελαφρύτερο βάρος.',progression:'Μονόπλευρη εκτέλεση.',reps:'10–12 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-7',type:'placeholder',motion:'press'}},
{id:8,name:'Dumbbell Row',gr:'Κωπηλατική με αλτήρα',group:'Πλάτη',equipment:'Αλτήρες',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Τράβηξε τον αλτήρα προς τα πλευρά κρατώντας τον κορμό σταθερό.',cues:['Ώμος χαμηλά','Αγκώνας προς τα πίσω','Μην στρίβεις τον κορμό'],cue:'Αγκώνας πίσω',mistakes:['Στροφή κορμού'],regression:'Ελαφρύτερο βάρος.',progression:'Αργή έκκεντρη φάση.',reps:'10–12/πλευρά',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-8',type:'placeholder',motion:'row'}},
{id:9,name:'Dumbbell Romanian Deadlift',gr:'Romanian Deadlift με αλτήρες',group:'Πόδια',equipment:'Αλτήρες',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Σπρώξε τα ισχία πίσω με ουδέτερη σπονδυλική στήλη.',cues:['Ισχία πίσω','Αλτήρες κοντά στα πόδια','Πλάτη ουδέτερη'],cue:'Ισχία πίσω',mistakes:['Στρογγύλεμα πλάτης'],regression:'Μικρότερο εύρος.',progression:'Μεγαλύτερη αντίσταση.',reps:'10–12 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-9',type:'placeholder',motion:'hinge'}},
{id:10,name:'Band Row',gr:'Κωπηλατική με λάστιχο',group:'Πλάτη',equipment:'Λάστιχα',level:'Beginner',goal:'Strength',secondary:[],instructions:'Τράβηξε το λάστιχο προς τον κορμό με τους ώμους χαμηλά.',cues:['Ωμοπλάτες πίσω','Αγκώνες κοντά','Έλεγχος επιστροφής'],cue:'Ωμοπλάτες πίσω',mistakes:['Σήκωμα ώμων'],regression:'Πιο ελαφρύ λάστιχο.',progression:'Πιο δυνατό λάστιχο.',reps:'12–15 επαναλήψεις',rest:30,safety:'Έλεγξε ότι το λάστιχο είναι ασφαλισμένο.',media:{id:'local-10',type:'placeholder',motion:'row'}},
{id:11,name:'Kettlebell Swing',gr:'Kettlebell Swing',group:'Full Body',equipment:'Kettlebell',level:'Intermediate',goal:'Power',secondary:[],instructions:'Παρήγαγε την κίνηση από τα ισχία και όχι από τα χέρια.',cues:['Ισχία δυνατά','Πλάτη ουδέτερη','Χέρια χαλαρά'],cue:'Ισχία δυνατά',mistakes:['Squat αντί hinge'],regression:'Ελαφρύτερο kettlebell.',progression:'Βαρύτερο kettlebell.',reps:'12–15 επαναλήψεις',rest:40,safety:'Απαιτεί ασφαλή τεχνική hinge.',media:{id:'local-11',type:'placeholder',motion:'swing'}},
{id:12,name:'TRX Row',gr:'TRX Row',group:'Πλάτη',equipment:'TRX',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Τράβηξε το σώμα προς τις λαβές κρατώντας ευθεία γραμμή.',cues:['Σταθερός κορμός','Ωμοπλάτες πίσω','Καρποί ουδέτεροι'],cue:'Σταθερός κορμός',mistakes:['Κάμψη ισχίων'],regression:'Πιο όρθια θέση.',progression:'Πιο οριζόντια θέση.',reps:'10–12 επαναλήψεις',rest:30,safety:'Έλεγξε την αγκύρωση του TRX.',media:{id:'local-12',type:'placeholder',motion:'row'}},
{id:13,name:'Battle Rope Waves',gr:'Battle Rope Waves',group:'Full Body',equipment:'Battle Ropes',level:'Intermediate',goal:'Conditioning',secondary:[],instructions:'Δημιούργησε εναλλάξ κύματα κρατώντας ελαφριά κάμψη στα γόνατα.',cues:['Σταθερός κορμός','Ώμοι χαμηλά','Σταθερός ρυθμός'],cue:'Σταθερός κορμός',mistakes:['Ένταση στον αυχένα'],regression:'Μικρότερα κύματα.',progression:'Μεγαλύτερη διάρκεια.',reps:'30–40s',rest:30,safety:'Διατήρησε ασφαλή απόσταση από τα σχοινιά.',media:{id:'local-13',type:'placeholder',motion:'ropes'}},
{id:14,name:'Glute Bridge',gr:'Γέφυρα γλουτών',group:'Γλουτοί',equipment:'Bodyweight',level:'Beginner',goal:'Strength',secondary:[],instructions:'Σήκωσε τη λεκάνη πιέζοντας τους γλουτούς χωρίς υπερέκταση.',cues:['Πίεσε τις φτέρνες','Σφίξε γλουτούς','Πλευρά μέσα'],cue:'Σφίξε γλουτούς',mistakes:['Υπερέκταση μέσης'],regression:'Μικρότερο εύρος.',progression:'Μονόποδη γέφυρα.',reps:'12–15 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-14',type:'placeholder',motion:'hinge'}},
{id:15,name:'Dead Bug',gr:'Dead Bug',group:'Κορμός',equipment:'Bodyweight',level:'Beginner',goal:'Balance',secondary:[],instructions:'Κατέβασε αντίθετο χέρι και πόδι κρατώντας τη μέση σταθερή.',cues:['Μέση σταθερή','Αργή κίνηση','Εκπνοή στην έκταση'],cue:'Μέση σταθερή',mistakes:['Αποκόλληση μέσης'],regression:'Κίνηση μόνο ποδιών.',progression:'Μεγαλύτερη έκταση.',reps:'8–10/πλευρά',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-15',type:'placeholder',motion:'functional'}},
{id:16,name:'Dumbbell Goblet Squat',gr:'Goblet Squat',group:'Πόδια',equipment:'Αλτήρες',level:'Intermediate',goal:'Strength',secondary:[],instructions:'Κράτησε τον αλτήρα μπροστά στο στήθος και κάθισε ελεγχόμενα.',cues:['Στήθος ψηλά','Γόνατα ακολουθούν πέλματα','Πίεσε το έδαφος'],cue:'Στήθος ψηλά',mistakes:['Γόνατα προς τα μέσα'],regression:'Ελαφρύτερο βάρος.',progression:'Βαρύτερο βάρος.',reps:'10–12 επαναλήψεις',rest:30,safety:'Σταμάτησε αν υπάρχει πόνος.',media:{id:'local-16',type:'placeholder',motion:'squat'}}
];
export const programs=[
{id:'p1',title:'Full Body 30',subtitle:'Ισορροπημένη functional προπόνηση',level:'Beginner',duration:30,equipment:'Bodyweight',focus:'Full Body',items:[2,1,3,4,14,15],work:40,rest:20,rounds:4},
{id:'p2',title:'Functional 40',subtitle:'Δύναμη και conditioning',level:'Intermediate',duration:40,equipment:'Bodyweight + Αλτήρες',focus:'Full Body',items:[16,8,7,9,5,4],work:45,rest:20,rounds:5},
{id:'p3',title:'Strength 45',subtitle:'Functional strength',level:'Intermediate',duration:45,equipment:'Αλτήρες + Λάστιχα + Kettlebell',focus:'Full Body',items:[16,8,9,7,10,11],work:45,rest:25,rounds:5},
{id:'p4',title:'Conditioning 30',subtitle:'Γρήγορη προπόνηση conditioning',level:'Intermediate',duration:30,equipment:'Bodyweight + Battle Ropes',focus:'Full Body',items:[13,5,6,2,1,4],work:35,rest:20,rounds:4},
{id:'p5',title:'Upper Body 40',subtitle:'Πλάτη, στήθος, ώμοι και χέρια',level:'Intermediate',duration:40,equipment:'Αλτήρες + Λάστιχα + TRX',focus:'Upper Body',items:[1,8,7,10,12,4],work:45,rest:20,rounds:5},
{id:'p6',title:'Lower Body 40',subtitle:'Πόδια και γλουτοί',level:'Intermediate',duration:40,equipment:'Bodyweight + Αλτήρες',focus:'Lower Body',items:[2,3,16,9,14,15],work:45,rest:20,rounds:5},
{id:'p7',title:'Advanced Functional 50',subtitle:'Προχωρημένη full-body προπόνηση',level:'Advanced',duration:50,equipment:'Mixed',focus:'Full Body',items:[6,11,13,16,8,7,9,5],work:45,rest:20,rounds:6},
{id:'p8',title:'Functional Complete 60',subtitle:'Πλήρης συνεδρία functional',level:'Intermediate',duration:60,equipment:'Mixed',focus:'Full Body',items:[2,16,8,7,9,10,11,12,13,5,4,15],work:45,rest:20,rounds:5}
];
export const equipmentOptions=['Όλα','Bodyweight','Αλτήρες','Λάστιχα','Kettlebell','TRX','Battle Ropes'];
export const levelOptions=['Όλα','Beginner','Intermediate','Advanced'];
export const groupOptions=['Όλα','Πόδια','Γλουτοί','Στήθος','Πλάτη','Ώμοι','Χέρια','Κορμός','Full Body'];
export const goalOptions=['Όλα','Strength','Conditioning','Endurance','Mobility','Balance','Power'];
