import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Dumbbell,Mic,Play,Pause,SkipForward,SkipBack,Search,Heart,Settings2,X,ChevronRight} from 'lucide-react';
import './styles.css';
import {exercises as canonicalExercises} from './data';
import {programs,PROGRAM_CATEGORIES} from './programs60';
import {loadOpenGym3DExercises} from './opengym3d';
import {loadDatasetExercises} from './dataset';
import {reformerPrograms} from './reformerData';
import ExerciseAnimation from './components/ExerciseAnimation';
import {buildTimeline,totalSeconds} from './engine/workout';

const fmt=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
const norm=s=>String(s||'').toLocaleLowerCase('el-GR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const speak=text=>{if(!text||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='el-GR';window.speechSynthesis.speak(u)};
function useStore(key,fallback){const[v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return[v,setV]}

function App(){
 const[tab,setTab]=useState('home'),[gif,setGif]=useState([]),[remote3d,setRemote3d]=useState([]),[gifStatus,setGifStatus]=useState('loading');
 const[q,setQ]=useState(''),[equipment,setEquipment]=useState('Όλα'),[group,setGroup]=useState('Όλα'),[goal,setGoal]=useState('Όλα'),[level,setLevel]=useState('Όλα');
 const[pLevel,setPLevel]=useState('Beginner'),[pType,setPType]=useState('Full Body'),[pEquipment,setPEquipment]=useState('Όλα');
 const[detail,setDetail]=useState(null),[active,setActive]=useState(null),[cursor,setCursor]=useState(0),[left,setLeft]=useState(0),[paused,setPaused]=useState(false),[listening,setListening]=useState(false);
 const[favorites,setFavorites]=useStore('ft_favorites',[]);
 useEffect(()=>{const c=new AbortController();loadDatasetExercises({signal:c.signal}).then(x=>{setGif(x.filter(e=>e.media?.imageUrl));setGifStatus('ready')}).catch(e=>{if(e.name!=='AbortError'){console.error(e);setGifStatus('error')}});loadOpenGym3DExercises({signal:c.signal}).then(setRemote3d).catch(()=>{});return()=>c.abort()},[]);
 const exercises=useMemo(()=>{
   const byName=new Map(gif.map(x=>[norm(x.name),x]));
   const threeD=new Map(remote3d.filter(x=>x.media3d).map(x=>[x.openGymId,x]));
   const canonical=canonicalExercises.map(x=>{const g=byName.get(norm(x.name))||byName.get(norm(x.gr)),m=threeD.get(x.openGymId);return{...(g||{}),...(m||{}),...x,media:g?.media||x.media,media3d:m?.media3d||x.media3d,level:g?.level||x.level||'Beginner'}});
   const names=new Set(canonical.map(x=>norm(x.name)));
   const gifOnly=gif.filter(x=>!names.has(norm(x.name)));
   return[...canonical,...gifOnly];
 },[gif,remote3d]);
 const countMap=key=>exercises.reduce((a,x)=>{const v=x[key];if(v)a[v]=(a[v]||0)+1;return a},{});
 const options=key=>{const c=countMap(key);return[{value:'Όλα',label:`Όλα (${exercises.length})`},...Object.entries(c).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).map(([value,n])=>({value,label:`${value} (${n})`}))]};
 const levelOptions=()=>{const c=countMap('level');return[{value:'Όλα',label:`Όλα (${exercises.length})`},...['Beginner','Advanced'].filter(x=>c[x]>0).map(value=>({value,label:`${value} (${c[value]})`}))]};
 const filtered=useMemo(()=>exercises.filter(x=>{const hay=norm([x.name,x.gr,x.group,x.equipment,x.goal,x.movement,...(x.primaryMuscles||[]),...(x.secondaryMuscles||[]),...(x.aliases||[])].join(' '));return(!q||hay.includes(norm(q)))&&(equipment==='Όλα'||x.equipment===equipment)&&(group==='Όλα'||x.group===group)&&(goal==='Όλα'||x.goal===goal)&&(level==='Όλα'||x.level===level)}),[exercises,q,equipment,group,goal,level]);
 const visiblePrograms=useMemo(()=>programs.filter(p=>p.level===pLevel&&p.type===pType&&(pEquipment==='Όλα'||p.equipment.includes?.(pEquipment)||p.equipment==='Mixed')),[pLevel,pType,pEquipment]);
 const timeline=active?buildTimeline(active,exercises):[],phase=timeline[cursor];
 useEffect(()=>{if(!active||paused||!phase)return;const t=setInterval(()=>setLeft(v=>{if(v>1)return v-1;const n=cursor+1;if(n>=timeline.length){setPaused(true);speak('Η προπόνηση ολοκληρώθηκε.');return 0}setCursor(n);return timeline[n].seconds}),1000);return()=>clearInterval(t)},[active,paused,phase,cursor]);
 const startProgram=p=>{const t=buildTimeline(p,exercises);if(!t.length)return;setActive(p);setCursor(0);setLeft(t[0].seconds);setPaused(false)};
 const move=d=>{if(!active)return;const n=Math.max(0,Math.min(timeline.length-1,cursor+d));setCursor(n);setLeft(timeline[n]?.seconds||0)};
 const toggleFav=id=>setFavorites(favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id]);
 const Filter=({label,value,set,options})=><div className="filterBlock"><label>{label}</label><div className="chips">{options.map(o=>{const x=typeof o==='string'?{value:o,label:o}:o;return <button key={x.value} className={value===x.value?'on':''} onClick={()=>set(x.value)}>{x.label}</button>})}</div></div>;
 const listen=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;const r=new SR();r.lang='el-GR';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=e=>{const t=norm(e.results[0][0].transcript);if(t.includes('χερ')){setGroup('Χέρια');setTab('library')}else if(t.includes('στηθ')){setGroup('Στήθος');setTab('library')}else if(t.includes('πλατ')){setGroup('Πλάτη');setTab('library')}else if(t.includes('ποδ')){setGroup('Πόδια');setTab('library')}else if(t.includes('κοιλια')||t.includes('κορμ')){setGroup('Κοιλιακοί');setTab('library')}else if(t.includes('ραχιαι')||t.includes('μεση')){setGroup('Ραχιαίοι');setTab('library')}else if(t.includes('stretch')){setGoal('Stretching');setTab('library')}else if(t.includes('flex')){setGoal('Flexibility');setTab('library')}else{setQ(e.results[0][0].transcript);setTab('library')}};r.start()};
 if(active&&phase){const ex=phase.exercise,elapsed=timeline.slice(0,cursor).reduce((a,b)=>a+b.seconds,0)+(phase.seconds-left),total=totalSeconds(timeline);return <div className="app"><header className="topbar"><button className="iconBtn" onClick={()=>setActive(null)}><X/></button><b>{active.title}</b><button className="iconBtn" onClick={listen}><Mic/></button></header><main className="main player">{phase.type==='work'?<ExerciseAnimation exercise={ex}/>:<div className="rest"><strong>{fmt(left)}</strong><span>ΔΙΑΛΕΙΜΜΑ</span></div>}<h1>{phase.type==='work'?ex.gr:'Διάλειμμα'}</h1><div className="timerCard"><strong>{fmt(left)}</strong></div><p className="muted">{fmt(Math.max(0,total-elapsed))} απομένουν</p></main><div className="playerDock"><button onClick={()=>move(-1)}><SkipBack/></button><button className="primaryCircle" onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</button><button onClick={()=>move(1)}><SkipForward/></button></div></div>}
 if(detail)return <div className="app"><header className="topbar"><button className="iconBtn" onClick={()=>setDetail(null)}><X/></button><b>Άσκηση</b><button className="iconBtn" onClick={()=>toggleFav(detail.id)}><Heart fill={favorites.includes(detail.id)?'currentColor':'none'}/></button></header><main className="main"><ExerciseAnimation exercise={detail}/><section className="detail"><p className="kicker">{detail.level} · {detail.equipment} · {detail.group}</p><h1>{detail.gr}</h1><small>{detail.name}</small><h3>Εκτέλεση</h3><p>{detail.instructions}</p><h3>Μύες</h3><p>{(detail.primaryMuscles||[]).join(' · ')}</p><h3>Coaching cues</h3><p>{(detail.cues||[]).join(' · ')}</p></section></main></div>;
 return <div className="app"><header className="topbar"><div className="brand"><span>ATHLETICO</span><strong>Fitness Trainer</strong></div><button className={`iconBtn ${listening?'listening':''}`} onClick={listen}><Mic/></button></header><main className="main">
 {tab==='home'&&<><section className="hero"><p className="kicker">FUNCTIONAL TRAINER</p><h1>Η προπόνησή σου.<br/>Με καθοδήγηση.</h1><p>{exercises.length} ασκήσεις · {exercises.filter(x=>x.media?.type==='animated-gif'&&x.media?.imageUrl).length} GIF animations {gifStatus==='error'?'· offline fallback ενεργό':''}</p></section><div className="quickGrid"><button onClick={()=>setTab('library')}><Dumbbell/>Ασκήσεις</button><button onClick={()=>setTab('programs')}><Play/>Functional 60'</button><button onClick={()=>setTab('reformer')}><Play/>Reformer</button><button onClick={()=>setTab('favorites')}><Heart/>Αγαπημένα</button></div></>}
 {tab==='library'&&<><div className="pageHead"><div><span>FUNCTIONAL LIBRARY</span><h1>Ασκησιολόγιο</h1></div></div><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Αναζήτηση άσκησης..."/></div><div className="filterPanel"><Filter label="Επίπεδο" value={level} set={setLevel} options={levelOptions()}/><Filter label="Εξοπλισμός" value={equipment} set={setEquipment} options={options('equipment')}/><Filter label="Μυϊκή ομάδα" value={group} set={setGroup} options={options('group')}/><Filter label="Στόχος" value={goal} set={setGoal} options={options('goal')}/></div><p className="resultMeta">{filtered.length} ασκήσεις</p><div className="exerciseGrid">{filtered.map(ex=><article className="exerciseCard" key={ex.id} onClick={()=>setDetail(ex)}><div className="exerciseVisual"><ExerciseAnimation exercise={ex} compact/></div><div className="exerciseContent"><div className="miniRow"><span>{ex.media?.type==='animated-gif'?'GIF · ':''}{ex.equipment}</span><button onClick={e=>{e.stopPropagation();toggleFav(ex.id)}}><Heart size={17} fill={favorites.includes(ex.id)?'currentColor':'none'}/></button></div><h3>{ex.gr}</h3><p>{ex.name}</p><div className="metaPills"><span>{ex.level}</span><span>{ex.group}</span></div></div></article>)}</div></>}
 {tab==='programs'&&<><div className="pageHead"><div><span>FUNCTIONAL · 60:00</span><h1>Προγράμματα</h1></div></div><Filter label="Επίπεδο" value={pLevel} set={setPLevel} options={['Beginner','Advanced']}/><Filter label="Μεθοδολογία" value={pType} set={setPType} options={PROGRAM_CATEGORIES}/><Filter label="Equipment" value={pEquipment} set={setPEquipment} options={['Όλα','Dumbbells','Barbell','Kettlebell','Bodyweight','TRX']}/><div className="programList">{visiblePrograms.map(p=><button className="programCard" key={p.id} onClick={()=>startProgram(p)}><div><span>{p.level} · {p.type} · 60:00</span><h3>{p.title}</h3><p>{p.subtitle}</p></div><ChevronRight/></button>)}</div></>}
 {tab==='reformer'&&<><div className="pageHead"><h1>Reformer</h1></div><div className="programList">{reformerPrograms.map(p=><article className="programCard reformerCard" key={p.id}><div><span>{p.level} · {p.duration}'</span><h3>{p.title}</h3><p>{p.focus}</p></div></article>)}</div></>}
 {tab==='favorites'&&<><div className="pageHead"><h1>Αγαπημένα</h1></div><div className="exerciseGrid">{exercises.filter(x=>favorites.includes(x.id)).map(ex=><article className="exerciseCard" key={ex.id} onClick={()=>setDetail(ex)}><div className="exerciseVisual"><ExerciseAnimation exercise={ex} compact/></div><div className="exerciseContent"><h3>{ex.gr}</h3><p>{ex.equipment} · {ex.group}</p></div></article>)}</div></>}
 </main><nav className="bottomNav"><button className={tab==='home'?'on':''} onClick={()=>setTab('home')}><Home/>Home</button><button className={tab==='library'?'on':''} onClick={()=>setTab('library')}><Dumbbell/>Ασκήσεις</button><button className="voiceNav" onClick={listen}><Mic/></button><button className={tab==='programs'?'on':''} onClick={()=>setTab('programs')}><Play/>Programs</button><button onClick={()=>setTab('home')}><Settings2/>Settings</button></nav></div>}
createRoot(document.getElementById('root')).render(<App/>);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{}));
