import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Dumbbell,Mic,Play,Pause,SkipForward,SkipBack,Search,Heart,History,Settings2,X,ChevronRight} from 'lucide-react';
import './styles.css';
import {exercises as localExercises,programs} from './data';
import {loadDatasetExercises,DATASET_REPO} from './dataset';
import {reformerPrograms} from './reformerData';
import ExerciseAnimation from './components/ExerciseAnimation';
import {buildTimeline,totalSeconds} from './engine/workout';

const speak=text=>{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='el-GR';u.rate=.94;window.speechSynthesis.speak(u)};
const fmt=s=>`${Math.floor(s/60)}:${String(Math.max(0,s%60)).padStart(2,'0')}`;
function useStore(key,fallback){const[v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return[v,setV]}

function App(){
 const[tab,setTab]=useState('home');
 const[datasetExercises,setDatasetExercises]=useState([]),[datasetStatus,setDatasetStatus]=useState('loading');
 const[q,setQ]=useState(''),[equipment,setEquipment]=useState('Όλα'),[level,setLevel]=useState('Όλα'),[group,setGroup]=useState('Όλα'),[goal,setGoal]=useState('Όλα');
 const[detail,setDetail]=useState(null),[active,setActive]=useState(null),[cursor,setCursor]=useState(0),[left,setLeft]=useState(0),[paused,setPaused]=useState(false);
 const[favorites,setFavorites]=useStore('ft_favorites',[]),[history,setHistory]=useStore('ft_history',[]),[voiceMode,setVoiceMode]=useStore('ft_voice','Coach');
 const[listening,setListening]=useState(false);
 useEffect(()=>{const c=new AbortController();loadDatasetExercises({signal:c.signal}).then(x=>{setDatasetExercises(x);setDatasetStatus('ready')}).catch(e=>{if(e.name!=='AbortError'){console.error(e);setDatasetStatus('error')}});return()=>c.abort()},[]);
 const exercises=useMemo(()=>[...localExercises,...datasetExercises],[datasetExercises]);
 const opt=key=>['Όλα',...Array.from(new Set(exercises.map(x=>x[key]).filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b),'el'))];
 const equipmentOptions=useMemo(()=>opt('equipment'),[exercises]);
 const levelOptions=useMemo(()=>opt('level'),[exercises]);
 const groupOptions=useMemo(()=>opt('group'),[exercises]);
 const goalOptions=useMemo(()=>opt('goal'),[exercises]);
 const filtered=useMemo(()=>exercises.filter(x=>{const hay=[x.name,x.gr,x.group,x.equipment,x.level,x.goal,x.target,x.muscleGroup,...(x.secondary||[])].join(' ').toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(equipment==='Όλα'||x.equipment===equipment)&&(level==='Όλα'||x.level===level)&&(group==='Όλα'||x.group===group)&&(goal==='Όλα'||x.goal===goal)}),[exercises,q,equipment,level,group,goal]);
 const timeline=active?buildTimeline(active,exercises):[];const phase=timeline[cursor];
 useEffect(()=>{if(!active||paused||!phase)return;const t=setInterval(()=>setLeft(v=>{if(v>1)return v-1;const n=cursor+1;if(n>=timeline.length){setPaused(true);speak('Ολοκλήρωσες το πρόγραμμα.');return 0}setCursor(n);const np=timeline[n];if(np.type==='work')speak(`Επόμενη άσκηση: ${np.exercise.gr}`);return np.seconds}),1000);return()=>clearInterval(t)},[active,paused,cursor,phase]);
 const startProgram=p=>{const t=buildTimeline(p,exercises);if(!t.length)return;setActive(p);setCursor(0);setLeft(t[0].seconds);setPaused(false);setHistory([{id:Date.now(),title:p.title,date:new Date().toLocaleString('el-GR')},...history].slice(0,30));speak(`Ξεκινάμε ${p.title}. Πρώτη άσκηση ${t[0].exercise.gr}`)};
 const move=d=>{if(!active)return;const n=Math.max(0,Math.min(timeline.length-1,cursor+d));setCursor(n);setLeft(timeline[n]?.seconds||0)};
 const listen=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Η φωνητική αναγνώριση δεν υποστηρίζεται σε αυτόν τον browser.');return}const r=new SR();r.lang='el-GR';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=e=>parseVoice(e.results[0][0].transcript.toLowerCase());r.start()};
 const parseVoice=t=>{if(active){if(t.includes('παύ')||t.includes('σταμάτ')){setPaused(true);return}speak('');if(t.includes('συνέχ')||t.includes('ξεκίνα')){setPaused(false);return}if(t.includes('επόμεν'))return move(1);if(t.includes('προηγ'))return move(-1)}if(t.includes('αρχάρι'))setLevel('Beginner');if(t.includes('μέτρι')||t.includes('intermediate'))setLevel('Intermediate');if(t.includes('προχωρ')||t.includes('advanced'))setLevel('Advanced');if(t.includes('αλτήρ')||t.includes('βαράκ'))setEquipment('Αλτήρες');if(t.includes('λάστιχ'))setEquipment('Λάστιχα');if(t.includes('πλάτ'))setGroup('Πλάτη');if(t.includes('πόδ'))setGroup('Πόδια');if(t.includes('χέρ'))setGroup('Χέρια');if(t.includes('κορμ')||t.includes('κοιλια'))setGroup('Κορμός');setTab('library')};
 const toggleFav=id=>setFavorites(favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id]);
 const Filter=({label,value,set,options})=><div className="filterBlock"><label>{label}</label><div className="chips">{options.map(x=><button key={x} className={value===x?'on':''} onClick={()=>set(x)}>{x}</button>)}</div></div>;

 if(active&&phase){const ex=phase.exercise;const next=timeline.slice(cursor+1).find(x=>x.type==='work');const elapsed=timeline.slice(0,cursor).reduce((a,b)=>a+b.seconds,0)+(phase.seconds-left);const total=totalSeconds(timeline);return <div className="app"><header className="topbar"><button className="iconBtn" onClick={()=>setActive(null)}><X/></button><div className="centerTitle"><b>{active.title}</b><small>{fmt(Math.max(0,total-elapsed))} απομένουν</small></div><button className="iconBtn" onClick={listen}><Mic/></button></header><div className="progress"><i style={{width:`${Math.min(100,total?elapsed/total*100:0)}%`}}/></div><main className="main player">{phase.type==='work'?<ExerciseAnimation exercise={ex}/>:<div className="rest"><strong>{fmt(left)}</strong><span>ΔΙΑΛΕΙΜΜΑ</span>{next&&<><p>Επόμενη</p><h2>{next.exercise.gr}</h2></>}</div>}<h1>{phase.type==='work'?ex.gr:'Ανάκτησε την αναπνοή σου'}</h1>{phase.type==='work'&&<p className="muted">{ex.instructions}</p>}<div className="timerCard"><span>{phase.type==='work'?'ΕΚΤΕΛΕΣΗ':'ΔΙΑΛΕΙΜΜΑ'}</span><strong>{fmt(left)}</strong><button onClick={()=>setLeft(v=>v+15)}>+15s</button></div>{phase.type==='work'&&voiceMode!=='Minimal'&&<div className="coach"><b>COACH</b><p>{(ex.cues||[]).join(' · ')}</p></div>}</main><div className="playerDock"><button onClick={()=>move(-1)}><SkipBack/></button><button className="primaryCircle" onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</button><button onClick={()=>move(1)}><SkipForward/></button><button onClick={listen}><Mic/></button></div></div>}

 if(detail)return <div className="app"><header className="topbar"><button className="iconBtn" onClick={()=>setDetail(null)}><X/></button><b>Άσκηση</b><button className="iconBtn" onClick={()=>toggleFav(detail.id)}><Heart fill={favorites.includes(detail.id)?'currentColor':'none'}/></button></header><main className="main"><ExerciseAnimation exercise={detail}/><section className="detail"><p className="kicker">{detail.level} · {detail.equipment} · {detail.goal}</p><h1>{detail.gr}</h1><small>{detail.name}</small><h3>Εκτέλεση</h3><p>{detail.instructions}</p>{detail.target&&<><h3>Μυϊκή στόχευση</h3><p>{detail.target}{detail.secondary?.length?` · ${detail.secondary.join(' · ')}`:''}</p></>}<h3>Coaching cues</h3><p>{(detail.cues||[]).join(' · ')||'—'}</p><div className="metricRow"><div><span>REPS / TIME</span><strong>{detail.reps}</strong></div><div><span>REST</span><strong>{detail.rest}s</strong></div></div>{detail.source==='free-exercise-db'&&<p className="sourceNote">Source: <a href={DATASET_REPO} target="_blank" rel="noreferrer">yuhonas/free-exercise-db</a> · Public Domain / Unlicense</p>}</section></main></div>;

 return <div className="app"><header className="topbar"><div className="brand"><span>ATHLETICO</span><strong>Fitness Trainer</strong></div><button className={`iconBtn ${listening?'listening':''}`} onClick={listen}><Mic/></button></header><main className="main">
 {tab==='home'&&<><section className="hero"><p className="kicker">VOICE-FIRST TRAINING</p><h1>Η προπόνησή σου.<br/>Με καθοδήγηση.</h1><p>{datasetStatus==='ready'?`${exercises.length} ασκήσεις διαθέσιμες με open-source previews.`:'Φόρτωση βιβλιοθήκης…'}</p><button className="voiceCTA" onClick={listen}><Mic/> Πες μου τι θέλεις</button></section><div className="quickGrid"><button onClick={()=>setTab('library')}><Dumbbell/>Ασκήσεις</button><button onClick={()=>setTab('programs')}><Play/>Functional</button><button onClick={()=>setTab('reformer')}><Play/>Reformer</button><button onClick={()=>setTab('favorites')}><Heart/>Αγαπημένα</button></div><section className="section"><div className="pageHead"><div><span>READY WORKOUTS</span><h2>Προτεινόμενα</h2></div></div><div className="programList">{programs.slice(0,4).map(p=><button className="programCard" key={p.id} onClick={()=>startProgram(p)}><div><span>{p.level} · {p.duration}'</span><h3>{p.title}</h3><p>{p.equipment}</p></div><ChevronRight/></button>)}</div></section></>}
 {tab==='library'&&<><div className="pageHead"><div><span>FUNCTIONAL</span><h1>Ασκησιολόγιο</h1></div></div><div className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Αναζήτηση άσκησης..."/></div><div className="filterPanel"><Filter label="Επίπεδο" value={level} set={setLevel} options={levelOptions}/><Filter label="Εξοπλισμός" value={equipment} set={setEquipment} options={equipmentOptions}/><Filter label="Μυϊκή ομάδα" value={group} set={setGroup} options={groupOptions}/><Filter label="Στόχος" value={goal} set={setGoal} options={goalOptions}/></div><p className="resultMeta">{filtered.length} ασκήσεις {datasetStatus==='error'?'· offline fallback':''}</p><div className="exerciseGrid">{filtered.map(ex=><article className="exerciseCard" key={ex.id} onClick={()=>setDetail(ex)}><div className="exerciseVisual"><ExerciseAnimation exercise={ex} compact/></div><div className="exerciseContent"><div className="miniRow"><span>{ex.level}</span><button onClick={e=>{e.stopPropagation();toggleFav(ex.id)}}><Heart size={17} fill={favorites.includes(ex.id)?'currentColor':'none'}/></button></div><h3>{ex.gr}</h3><p>{ex.name}</p><div className="metaPills"><span>{ex.equipment}</span><span>{ex.group}</span><span>{ex.goal}</span></div></div></article>)}</div></>}
 {tab==='programs'&&<><div className="pageHead"><div><span>FUNCTIONAL</span><h1>Προγράμματα</h1></div></div><div className="programList">{programs.map(p=><button className="programCard" key={p.id} onClick={()=>startProgram(p)}><div><span>{p.level} · {p.duration}'</span><h3>{p.title}</h3><p>{p.equipment}</p></div><ChevronRight/></button>)}</div></>}
 {tab==='reformer'&&<><div className="pageHead"><div><span>PILATES REFORMER</span><h1>50' Προγράμματα</h1></div></div><div className="programList">{reformerPrograms.map(p=><article className="programCard reformerCard" key={p.id}><div><span>{p.level} · {p.duration}'</span><h3>{p.title}</h3><p>{p.focus}</p><small>{p.blocks.map(b=>b.name).join(' · ')}</small></div></article>)}</div></>}
 {tab==='favorites'&&<><div className="pageHead"><div><span>SAVED</span><h1>Αγαπημένα</h1></div></div><div className="exerciseGrid">{exercises.filter(x=>favorites.includes(x.id)).map(ex=><article className="exerciseCard" key={ex.id} onClick={()=>setDetail(ex)}><div className="exerciseVisual"><ExerciseAnimation exercise={ex} compact/></div><div className="exerciseContent"><h3>{ex.gr}</h3><p>{ex.equipment} · {ex.level}</p></div></article>)}</div></>}
 {tab==='history'&&<><div className="pageHead"><div><span>ACTIVITY</span><h1>Ιστορικό</h1></div></div>{history.map(h=><div className="historyCard" key={h.id}><History/><div><b>{h.title}</b><span>{h.date}</span></div></div>)}</>}
 {tab==='settings'&&<><div className="pageHead"><div><span>PREFERENCES</span><h1>Ρυθμίσεις</h1></div></div><div className="settingsCard"><span>Voice guidance</span><div className="seg">{['Minimal','Normal','Coach'].map(x=><button key={x} className={voiceMode===x?'on':''} onClick={()=>setVoiceMode(x)}>{x}</button>)}</div></div></>}
 </main><nav className="bottomNav"><button className={tab==='home'?'on':''} onClick={()=>setTab('home')}><Home/>Home</button><button className={tab==='library'?'on':''} onClick={()=>setTab('library')}><Dumbbell/>Ασκήσεις</button><button className="voiceNav" onClick={listen}><Mic/></button><button className={tab==='programs'?'on':''} onClick={()=>setTab('programs')}><Play/>Programs</button><button className={tab==='settings'?'on':''} onClick={()=>setTab('settings')}><Settings2/>Settings</button></nav></div>
}
createRoot(document.getElementById('root')).render(<App/>);
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{}));}
