// Athletico Functional ready programs. Beginner/Advanced only; every session is exactly 3600 seconds.
const block=(ids,duration,work,rest,label)=>{const out=[];let left=duration,i=0;while(left>0){const w=Math.min(work,left);out.push({type:'work',exerciseId:ids[i%ids.length],seconds:w,label});left-=w;i++;if(left<=0)break;const r=Math.min(rest,left);out.push({type:'rest',seconds:r,label:`${label} · RECOVERY`});left-=r;}return out};
const phase=(ids,min,work,rest,label)=>block(ids,min*60,work,rest,label);
const session=(ids,work,rest,level)=>[...phase(ids.slice(0,4),8,40,20,'WARM-UP'),...phase(ids.slice(1,5),10,45,15,'MOBILITY + ACTIVATION'),...phase(ids,15,level==='Beginner'?55:70,level==='Beginner'?35:20,'TECHNIQUE / CONTROL'),...phase(ids,22,work,rest,'MAIN WORK'),...phase(ids.slice(0,3),5,40,20,'COOL DOWN')];
const make=(meta,segments)=>{const seconds=segments.reduce((n,s)=>n+s.seconds,0);if(seconds!==3600)throw new Error(`${meta.id}: ${seconds}s, expected 3600`);return {...meta,duration:60,seconds,segments};};
export const PROGRAM_CATEGORIES=['Full Body','Strength','Conditioning','Mobility','Flexibility','Stretching'];
const P={full:['local:squat','local:push_up','local:reverse_lunge','local:dumbbell_row','local:dumbbell_romanian_deadlift','local:farmer_carry'],strength:['local:back_squat','local:deadlift','local:bent_over_row','local:overhead_press','local:dumbbell_split_squat','local:renegade_row'],conditioning:['local:kettlebell_swing','local:burpee','local:mountain_climber','local:dumbbell_thruster','local:battle_rope_waves','local:reverse_lunge'],mobility:['local:inchworm','local:lateral_lunge','local:split_squat','local:overhead_squat','local:dead_bug','local:reverse_lunge'],flexibility:['local:inchworm','local:lateral_lunge','local:reverse_lunge','local:single_leg_glute_bridge','local:dead_bug','local:split_squat'],stretching:['local:inchworm','local:lateral_lunge','local:reverse_lunge','local:single_leg_glute_bridge','local:dead_bug','local:side_plank']};
const specs=[['Full Body','full'],['Strength','strength'],['Conditioning','conditioning'],['Mobility','mobility'],['Flexibility','flexibility'],['Stretching','stretching']];
const rotate=(a,n)=>a.slice(n).concat(a.slice(0,n));
const advanced=a=>a.map((id,i)=>i===0?'local:clean_and_jerk':i===3?'local:snatch':id);
const ratios=(type,level)=>['Flexibility','Stretching','Mobility'].includes(type)?(level==='Beginner'?[50,10]:[55,5]):(level==='Beginner'?[40,20]:[50,10]);
export const programs=['Beginner','Advanced'].flatMap(level=>specs.flatMap(([type,key])=>[1,2,3,4].map(variant=>{let ids=rotate(P[key],(variant-1)%P[key].length);if(level==='Advanced'&&['Full Body','Strength','Conditioning'].includes(type))ids=advanced(ids);const [work,rest]=ratios(type,level);const slug=type.toLowerCase().replaceAll(' ','-');return make({id:`${level[0].toLowerCase()}-${slug}-${String(variant).padStart(2,'0')}`,title:`${level} ${type} ${String(variant).padStart(2,'0')}`,subtitle:`60 λεπτά ${type} · Athletico Functional.`,level,type,methodology:type,equipment:'Mixed',focus:type,variant},session(ids,work,rest,level));})));
export const validatePrograms=()=>programs.length===48&&programs.every(p=>p.seconds===3600&&['Beginner','Advanced'].includes(p.level));
